services:
  - type: web
    name: ca-chatbot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python api_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: False
    autoDeploy: true
    healthCheckPath: /health
    plan: starter
