services:
  - type: web
    name: ca-chatbot-minimal
    env: python
    runtime: python-3.11.9
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir --only-binary=all -r requirements.txt || pip install --no-cache-dir -r requirements-minimal.txt
    startCommand: |
      gunicorn api_server:app -c gunicorn.conf.py
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: DEBUG
        value: "false"
      - key: PYTHONPATH
        value: "."
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PIP_NO_BUILD_ISOLATION
        value: "false"
      - key: PIP_PREFER_BINARY
        value: "1"
    healthCheckPath: /health
    autoDeploy: true
    plan: starter
